defaults:
  - common
  - agent: sac

max_steps: 1e8
robot: HumanoidAMASSPC
keep_checkpoints: 2e6
eval:
  interval: 100000
  metrics:
    score: sum:default

slurm:
  cpus_per_task: 7

env:
  name: BiskGoToTargetsC-v1
  train_procs: 5
  eval_procs: 50
  args:
    robot: ${robot}
    features: comic
  wrappers:
    - flatten_obs

agent:
  batch_size: 256
  rpbuf_size: 5000000
  randexp_samples: 10000
  warmup_samples: 10000
  rpbuf_device: cpu
  samples_per_update: 300
  num_updates: 50
  alpha: 1

video: null # not during trainng
visdom:
  offline: true

model:
  pi: pi_d2rl_256
  q: qd_d2rl_256

optim:
  pi:
    _target_: torch.optim.Adam
    lr: 3e-4
    fuse: true
  q: ${optim.pi}
