name: 'guidedsac'
gamma: 0.99  # discount factor
polyak: 0.995  # polyak step size for updating target network
batch_size: 256
rpbuf_size: 1e6  # replay buffer size
rpbuf_device: auto
samples_per_update: 50  # perform updates every N samples
num_updates: ${agent.samples_per_update}
warmup_samples: 1000
randexp_samples: 1000
clip_grad_norm: 0.0 # only used if > 0
tanh_actions: true
normalize_actions: false
action_cost: 0.0
action_cost_type: square
entropy_mean: false

alpha: 0.1
target_entropy_factor: 1.0
optim_alpha:
  _target_: torch.optim.Adam
  lr: 1e-4

guide:
  path: null # guidance model
  model: from_path
  temp: 0
  c: 0 # how many guidance steps + 1
  r: 0 # rate for number of guidance steps min(c, (will be possion(r) + 1))
  p: 0 # probability of using guide
  p_anneal: 0 # anneal guide.p towards 0 across this many samples (or don't anneal)
  ctx: 1 # how many past actions to use for conditioning
  exclude_samples: true # whether to use samples from guide for training
  num_cond: 1 # how many classes for conditioning (if any)
  cond: null

policy_lo:
  cond_key: z
  cond_dim: 32
  obs_key: observation
hide_obs_lo_from_hi: false

graph: true
